name: CypressTests1
on: [push, workflow_dispatch]

jobs:
  cypress:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npx cypress run 
      - run: npx cypress run --record 
        env:
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

